# The secrets file should not be checked into Git. It's published only for demonstration purpose.
secretGenerator:
- name: mysql-root-pass
  literals:
  - password=password
- name: mysql-user-pass
  literals:
  - username=user
  - password=password 
- name: mysql-db-url
  literals:
  - database=users_database
  - url=jdbc:mysql://database:3306/users_database?useSSL=false
resources:
  - mysql-deployment.yaml
  - app-server.yaml
  - app-client.yaml  
  # use one
