version: '3.7'
services:
  database:
    image: mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
     - dockerAngularSpringDatabaseData:/var/lib/mysql
    networks:
     - backendNetwork

  springapp:
    build: ./springboot2-jpa-crud-example
    container_name: springapp
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
       SPRING.DATASOURCE_URL: jdbc:mysql://database:3306/users_database?useSSL=false
       SPRING_DATASOURCE_USERNAME: user
       SPRING_DATASOURCE_PASSWORD: password
    networks:
      - backendNetwork
      - frontendNetwork
  angular:
    build: ./angular8-springboot-client
    container_name: angular
    ports:
      - 4200:80
    depends_on:
      - springapp

    networks:
      - frontendNetwork
volumes:
  dockerAngularSpringDatabaseData:

networks:
  backendNetwork:
  frontendNetwork:
